name: run-tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [8.0, 8.1]
                laravel: [^8.71, 9.*]
                stability: [prefer-lowest, prefer-stable]
                include:
                  - laravel: 8.*
                    testbench: ^6.6
                  - laravel: 9.*
                    testbench: ^7.0

        name: Unit test - P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv, fileinfo
                  coverage: pcov

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction
            - name: Execute tests
              run: vendor/bin/phpunit

    phpstan:
        name: Static analysis
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Cache Composer dependencies
              uses: actions/cache@v1
              with:
                  path: vendor
                  key: composer-${{ hashFiles('composer.lock') }}
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  coverage: none
            - name: Install Composer dependencies
              run: composer install --ignore-platform-reqs --no-scripts
            - name: Run phpstan
              run: composer phpstan

    cs-fixer:
        name: Code style fixer
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Cache Composer dependencies
              uses: actions/cache@v1
              with:
                path: vendor
                key: composer-${{ hashFiles('composer.lock') }}
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  coverage: none
            - name: Install Composer dependencies
              run: composer install --ignore-platform-reqs --no-scripts
            - name: Run php-cs-fixer
              run: composer fix
            - name: Commit changes from php-cs-fixer
              uses: EndBug/add-and-commit@v7
              with:
                  default_author: github_actions
